_target_: models.FlowMatchingDock.FlowMatchingDock

model:
  lm_embed_dim: 1301 # 1280 (ESM) + 21 (One-Hot) 
  positional_embed_dim: 67 # 66 (relpos) + 1 (sym)
  spatial_embed_dim: 100 # 40 (dist) + 24 (phi) + 24 (psi) + 12 (omega) 
  node_dim: 256
  edge_dim: 128
  inner_dim: 128
  depth: 6
  dropout: 0.1
  cut_off: 20.0
  coord_scale: 1.0
  normalize: True
  agg: 'mean'
  add_t_embedding: False
  correct_inertia: False
  scale_by_t_mlp: True
  sep_t_mlp_for_tr_rot: False

experiment:
  lr: 1e-4
  weight_decay: 0.0
  crop_size: 1200
  perturb_tr: True
  perturb_rot: True
  separate_energy_loss: True
  separate_tr_loss: True
  separate_rot_loss: True
  grad_energy: False
  use_contrastive_loss: False
  use_confidence_loss: False
  use_dist_loss: False
  use_interface_loss: False
  use_v_loss: False
  tr_sigma_max: 5.0
  tr_sigma_min: 0.1
  rot_sigma_max: 0.5
  rot_sigma_min: 0.01
  restricted_perturb_tr: False
  com_vec_rot_sigma: 0.8
  scale_pred_by_t: False
  pred_distance: False
  scale_f_norm: 'none'
  scale_tr_loss_by_sigma_max: False
  scale_tr_loss_by_sigma_t: False
  use_gt_v_for_e: False
